<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="radius" value="0.05"/>
  <xacro:property name="length" value="0.1"/>
  <xacro:property name="test" value="${radius*length}"/>

  <xacro:macro name="vacuum_gripper_urdf" params="prefix">
    <!-- link list -->
    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 ${length / 2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${radius}" length="${length}" />
        </geometry>
        <material name="red">
          <color rgba="1 0 0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${length / 2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${length}"/>
        </geometry>
        <material name="red"/>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.0000063" ixy="0" ixz="0"
                 iyy="0.0000063" iyz="0"
                 izz="0.000025" />
        <mass value="0.01" />
      </inertial>
    </link>
    <link name="${prefix}tool0"/>
    <!-- joint list -->
    <joint name="vacuum_gripper_joint" type="fixed">
      <origin xyz="0 0 ${length}" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}tool0" />
    </joint>
  </xacro:macro>
</robot>
