<?xml version="1.0"?>
<robot name="linear_actuator_urdf" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="width" value="0.2" />
  <xacro:property name="length" value="4.6" />
  <xacro:property name="height" value="0.1" />
  <xacro:property name="carriage_length" value="0.2"/>

  <xacro:macro name="linear_actuator_urdf" params="prefix">
    <!-- link list -->
    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 ${height / 2}" rpy="0 0 0" />
        <geometry>
          <box size="${width} ${length} ${height}" />
        </geometry>
        <material name="grey">
          <color rgba="0.2 0.2 0.2 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${height / 2}" rpy="0 0 0" />
        <geometry>
          <box size="${width} ${length} ${height}" />
        </geometry>
        <material name="grey"/>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.1" ixy="0" ixz="0"
                 iyy="0.1" iyz="0"
                 izz="0.1" />
        <mass value="1" />
      </inertial>
    </link>
    <link name="${prefix}carriage">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.1" ixy="0" ixz="0"
                 iyy="0.1" iyz="0"
                 izz="0.1" />
        <mass value="1" />
      </inertial>
    </link>

    <!-- joint list -->
    <joint name="${prefix}carriage_joint" type="prismatic">
      <parent link="${prefix}base_link" />
      <child link="${prefix}carriage" />
      <origin xyz="0 0 ${height}" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <limit lower="-${(length / 2) - carriage_length}"
             upper="${(length / 2) - carriage_length}"
             effort="1000"
             velocity="3" />
      <dynamics damping="0.7" friction="500.0" />
    </joint>
  </xacro:macro>
</robot>
