part_list:
 - name: disk 
   path: /model/disk.pcd
   pick_point_index: 137
 - name: gear
   path: /model/gear.pcd
   pick_point_index: 40
 - name: piston_rod
   path: /model/piston_rod.pcd
   pick_point_index: 48
pick_orientation:
 x: 0
 y: 1
 z: 0
 w: 0
