parameters:
  descr_rad: 0.08
  down_sample: 0.007
  min_sample_distance: 0.02
  max_correspondence_distance: 0.01
  nr_iterations: 500
switches:
  visualizer: false
camera_roi:
  x: [-0.68, 0.68]
  y: [-0.2, 0.44]
  z: [0.0, 1.19]
